name: 'My Python Action'
description: 'A simple action that runs a Python script'
inputs:
  example_input:
    description: 'An example input'
    required: false
    default: 'Hello World'
runs:
  using: 'python'
  main: 'main.py'
