name: "Greet User"
description: "A simple action to greet a user."
inputs:
  name:
    description: "The name of the user to greet"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - name: Greet User
      run: echo "Hello, ${{ inputs.name }}!"
