name: "Greet User"
description: "A GitHub Action that greets the user"
inputs:
  name:
    description: "Name of the user"
    required: true
    default: "GitHub User"
runs:
  using: "docker"
  image: "Dockerfile"
