name: Test Custom Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run My Python Action
        uses: ./.github/actions/my-python-action
        with:
          example_input: 'Test input for my action'
