name: Deploy to Render

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Render Deploy
        uses: render-examples/render-deploy@v1.0.0
        with:
          render_api_key: ${{ secrets.RENDER_API_KEY }}  
          service_id: srv-cskdqojtq21c73dmtjr0 
